### ISSUE TITLE
Webpack 5 support?

### ISSUE THREAD

**Issue by osmestad** [Runjuu/html-inline-css-webpack-plugin#28]
Hi, I'm trying to update a project to Webpack 5, but I'm getting an error I suspect is from this plugin:

```
Building(node:30678) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at /Users/osmestad/Code/webclient-app/node_modules/html-inline-css-webpack-plugin/build/core/base-plugin.js:34:39
    at Array.forEach (<anonymous>)
    at PluginForHtmlWebpackPluginV4.BasePlugin.prepare (/Users/osmestad/Code/webclient-app/node_modules/html-inline-css-webpack-plugin/build/core/base-plugin.js:30:33)
    at /Users/osmestad/Code/webclient-app/node_modules/html-inline-css-webpack-plugin/build/core/v4.js:69:27
    at eval (eval at create (/Users/osmestad/Code/webclient-app/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:17:16)
    at new Promise (<anonymous>)
    at AsyncSeriesWaterfallHook.eval [as promise] (eval at create (/Users/osmestad/Code/webclient-app/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/osmestad/Code/webclient-app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/osmestad/Code/webclient-app/node_modules/html-webpack-plugin/index.js:187:84
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Versions used:
"webpack": "5.4.0"
"html-webpack-plugin": "4.5.0",
"mini-css-extract-plugin": "1.3.0",
"html-inline-css-webpack-plugin": "1.9.0",

Is Webpack 5 support planned?

**Comment by osmestad** [comment]
Update: I guess it is a warning not error (yet) as the build seems to pass when I cleared up some other errors :-)

**Comment by Runjuu** [comment]
Hi @osmestad , I will take a look in a few days. 😉

**Comment by Runjuu** [comment]
@osmestad It seems like the warning is caused by `html-webpack-plugin` ([issue](https://github.com/jantimon/html-webpack-plugin/issues/1523)). I've tried the alpha version of `html-webpack-plugin` and the warning is gone 😜.

**Comment by osmestad** [comment]
Aha, thank you for looking into it!
I'll close this and assume the warning disappears when that package gets updated then :-)
