### ISSUE TITLE
TypeError: html.replace is not a function

### ISSUE THREAD

**Issue by dzotos** [Runjuu/html-inline-css-webpack-plugin#7]
Thanks for the plugin, but unfortunately I'm getting this error when using it.

```
emitting html-inline-css-webpack-plugin(node:946) UnhandledPromiseRejectionWarning: TypeError: html.replace is not a function
    at Function.Plugin.addStyle (/Users/dimitris/blueground/website/node_modules/html-inline-css-webpack-plugin/build/index.js:28:25)
    at /Users/dimitris/blueground/website/node_modules/html-inline-css-webpack-plugin/build/index.js:76:35
    at Array.forEach (<anonymous>)
    at /Users/dimitris/blueground/website/node_modules/html-inline-css-webpack-plugin/build/index.js:75:40
    at Array.forEach (<anonymous>)
    at Plugin.process (/Users/dimitris/blueground/website/node_modules/html-inline-css-webpack-plugin/build/index.js:73:36)
    at /Users/dimitris/blueground/website/node_modules/html-inline-css-webpack-plugin/build/index.js:94:23
    at _err6 (eval at create (/Users/dimitris/blueground/website/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:61:1)
    at emitHtmlPromise.then (/Users/dimitris/blueground/website/node_modules/html-webpack-plugin/index.js:313:11)
(node:946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

package.json

```
"webpack": "^4.28.4",
"html-webpack-plugin": "^4.0.0-beta.5",
"html-webpack-inline-source-plugin": "^1.0.0-beta.2",
```

**Comment by Runjuu** [comment]
Feel free to reopen it again if the problem still exist.
